# Generated by Django 2.2.4 on 2019-11-20 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_auto_20191120_1732'),
        ('zo', '0003_auto_20191114_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userhubsignup',
            old_name='hub_phone',
            new_name='hub_phone_number',
        ),
        migrations.RenameField(
            model_name='usersignup',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='userhubsignup',
            name='hub_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_hub_signup', to='hub.HubType'),
        ),
        migrations.AlterField(
            model_name='agegrade',
            name='under',
            field=models.NullBooleanField(default=None),
        ),
    ]
