# Generated by Django 2.2.4 on 2019-11-25 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zo', '0004_auto_20191120_1732'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='agegrade',
            managers=[
            ],
        ),
    ]
