# Generated by Django 2.2.4 on 2019-11-25 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zo', '0005_auto_20191126_0847'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='grade',
            managers=[
            ],
        ),
    ]
