# Generated by Django 2.2.4 on 2019-11-27 00:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zo', '0006_auto_20191126_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agegrade',
            name='date',
        ),
        migrations.AddField(
            model_name='agegrade',
            name='date_day',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AddField(
            model_name='agegrade',
            name='date_month',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='agegrade',
            name='age',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
