# Generated by Django 2.2.4 on 2019-12-27 04:22

from django.db import migrations
import zo.custom.model_fields.custom_distance


class Migration(migrations.Migration):

    dependencies = [
        ('zo', '0008_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='distance2',
            field=zo.custom.model_fields.custom_distance.CustomDistanceField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
