# Generated by Django 2.2.4 on 2019-12-27 06:15

from django.db import migrations, models
import zo.custom.model_fields.custom_distance


class Migration(migrations.Migration):

    dependencies = [
        ('zo', '0009_test_distance2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', zo.custom.model_fields.custom_distance.CustomDistanceField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='test',
            name='distance2',
        ),
    ]
