# Generated by Django 2.2.4 on 2019-12-31 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zo', '0010_auto_20191227_1915'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
