# Generated by Django 2.2.4 on 2019-11-14 00:45

import colorful.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zo', '0003_auto_20191114_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='HubGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('colour', colorful.fields.RGBColorField(blank=True)),
                ('text_colour', colorful.fields.RGBColorField(blank=True, colors=['#000000', '#ffffff'])),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hub_groups', to='hub.Hub')),
            ],
        ),
        migrations.CreateModel(
            name='HubGroupMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(blank=True, max_length=50)),
                ('hub_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='hub.HubGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HubGroupRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('rank_value', models.PositiveIntegerField(blank=True)),
                ('rank_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranks', to='hub.HubGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HubGroupRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
                ('hub_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='hub.HubGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HubRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hub_rank_name', models.CharField(max_length=30)),
                ('hub_rank_description', models.TextField(blank=True)),
                ('hub_rank_value', models.PositiveIntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='HubRankMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HubRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hub_roles', to='hub.Hub')),
                ('requisite_role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisite_roles', to='hub.HubRole')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HubRoleMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HubTypeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HubUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(blank=True)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hub_users', to='zo.Gender')),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hub_users', to='hub.Hub')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hubs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HubUserName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, verbose_name='First Name')),
                ('middlenames', models.CharField(blank=True, max_length=50, verbose_name='Middle Name/s')),
                ('surname', models.CharField(max_length=30)),
                ('preferred_name', models.CharField(blank=True, default='', max_length=50, verbose_name='Preferred Name')),
                ('hub_member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='name', to='hub.HubUser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='hub.HubTypeCategory')),
            ],
        ),
        migrations.CreateModel(
            name='HubRoleMembershipPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_periods', to='hub.HubRoleMembership')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='hubrolemembership',
            name='hub_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_memberships', to='hub.HubUser'),
        ),
        migrations.AddField(
            model_name='hubrolemembership',
            name='requisite_users',
            field=models.ManyToManyField(related_name='requisite_role_memberships', to='hub.HubUser'),
        ),
        migrations.AddField(
            model_name='hubrolemembership',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='hub.HubRole'),
        ),
        migrations.CreateModel(
            name='HubRankMembershipPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_periods', to='hub.HubRankMembership')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='hubrankmembership',
            name='hub_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_memberships', to='hub.HubUser'),
        ),
        migrations.AddField(
            model_name='hubrankmembership',
            name='rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='hub.HubRank'),
        ),
        migrations.CreateModel(
            name='HubRankGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hub_rank_groups', to='hub.Hub')),
                ('types', models.ManyToManyField(related_name='hub_rank_groups', to='zo.RankGroupType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='hubrank',
            name='hub_rank_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hub_ranks', to='hub.HubRankGroup'),
        ),
        migrations.AddField(
            model_name='hubrank',
            name='rank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hub_ranks', to='zo.Rank'),
        ),
        migrations.CreateModel(
            name='HubGroupRoleMembershipPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True)),
                ('hub_group_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_periods', to='hub.HubGroupRole')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_membership_periods', to='hub.HubGroupMembership')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HubGroupRankMembershipPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True)),
                ('hub_group_rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_periods', to='hub.HubGroupRank')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_membership_periods', to='hub.HubGroupMembership')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HubGroupMemberShipPeriods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_periods', to='hub.HubGroupMembership')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HubClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hub_classifications', to='zo.Grade')),
                ('hub', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hub_classification', to='hub.Hub')),
                ('hub_types', models.ManyToManyField(related_name='hub_classification', to='hub.HubType')),
            ],
        ),
        migrations.CreateModel(
            name='HubAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(max_length=50, verbose_name='Address Line 1')),
                ('line2', models.CharField(blank=True, max_length=50, verbose_name='Address Line 2')),
                ('line3', models.CharField(blank=True, max_length=50, verbose_name='Address Line 3')),
                ('town_city', models.CharField(max_length=50, verbose_name='Town/City')),
                ('postcode', models.CharField(blank=True, max_length=50, verbose_name='Postcode')),
                ('country', models.CharField(blank=True, max_length=50, verbose_name='Country')),
                ('hub', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='hub.Hub')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
