# Generated by Django 2.2.4 on 2019-11-20 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hubclassification',
            name='hub_types',
        ),
        migrations.AddField(
            model_name='hubclassification',
            name='hub_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hub_classification', to='hub.HubType'),
        ),
    ]
