# Generated by Django 2.2.4 on 2019-11-22 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_auto_20191120_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hubusername',
            old_name='hub_member',
            new_name='hub_user',
        ),
    ]
